[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rviz_marker_tools_ros2"
version = "0.1.0"
description = "RViz Marker Tools for ROS2"
readme = "README.md"
# requires-python = ">=3.10"
maintainers = [
    {name = "Andrew Lui", email = "ak.lui@qut.edu.au"}
]
# Python dependencies go here (system/ROS deps still go in package.xml)
dependencies = [
    "setuptools",
    "pyyaml",
    "ipykernel",
    "catkin_pkg",
    "transforms3d",
    "numpy",
    "opencv_contrib_python",
    "pytest",
    "ruff",
    "pydocstringformatter",
]

[project.scripts]
basic_marker = "examples.basic_marker:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["rviz_marker", "examples"]
exclude = []

[tool.setuptools.data-files]
# "share/ament_index/resource_index/packages" = ["rviz_marker_tools_ros2"]
"share/rviz_marker_tools_ros2" = ["package.xml"]
"share/rviz_marker_tools_ros2/launch" = ["launch/example.launch"]
