name: Colcon Test Package in Docker Container 

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  spin-up-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
      checks: write
      id-token: write

    environment:
      name: docker-image
      deployment: false

    defaults:
      run:
        working-directory: ./docker

    steps:
      # fetch the repository code
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/ref-ras/ros2:latest

      # spin up docker compose service ros2 and execute colcon test
      - name: Execute Colcon Tests
        run: |
          docker compose run --rm ros2-test bash -c "
            source /opt/ros/\$ROS_DISTRO/setup.bash &&
            cd /workspace/ros2_ws &&
            colcon build &&
            source install/setup.bash &&
            colcon test --event-handlers console_cohesion+ &&
            colcon test-result --all
          "
      # publish test report
      - name: Publish Test Report Dashboard
        uses: mikepenz/action-junit-report@v6
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      # clean up resources to prevent leaks
      - name: Tear Down Containers
        if: always()
        run: |
          cd docker &&
          docker compose down --volumes
